### ISSUE TITLE
Group python Kiota repositories

### ISSUE THREAD

**Issue by andrueastman** [microsoft/kiota-abstractions-python#302]
Related to https://github.com/microsoft/kiota/issues/4636 and https://github.com/microsoft/kiota-abstractions-dotnet/issues/238

As a language specific concern, we should look into the feasibility of grouping the repos and outline if this is not feasible in this issue.

**Comment by musale** [comment]
This one will be an interesting one. I have come across tooling like [pants](https://www.pantsbuild.org/) that supports Go, Java, Python, Scala, Kotlin, and Shell. It's also open source https://github.com/pantsbuild/pants

**Comment by andrueastman** [comment]
Thats great!.

You can do the work as PR to this repo. Then we will rename it similar to work done for the dotnet migrations at https://github.com/microsoft/kiota-dotnet/pull/262.

**Comment by andrueastman** [comment]
[note for implementation/design] See https://github.com/microsoft/kiota-abstractions-python/issues/89 for more insights.

**Comment by baywet** [comment]
Whenever this is completed we should also:
- update the quickstart samples https://github.com/microsoft/kiota-samples/pull/6457
- update the quickstart documenation https://github.com/MicrosoftDocs/openapi-docs/pull/110
